---
# tasks file for ansible-apache

- name: "install apache2"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - apache2
    - libapache2-mod-scgi
  tags:
    install

- name: "install php7.0 modules"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - php
    - libapache2-mod-php
  when:
      ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"
  tags:
    php
    scgi

- name: "install php5 modules"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - php5
  when:
      ansible_distribution == "Ubuntu" and ansible_distribution_version < "16.04"
  tags:
    php
    scgi

- name: "enable scgi apache modules"
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - scgi
  notify:
    - restart apache
  tags:
    php
    scgi

- name: "enable php7.0 apache modules"
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - php7.0
  notify:
    - restart apache
  when:
      ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"
  tags:
    php
    scgi

- name: "enable php5 apache modules"
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - php5
  notify:
    - restart apache
  when:
      ansible_distribution == "Ubuntu" and ansible_distribution_version < "16.04"
  tags:
    php
    scgi

- name: "enable apache ssl modules"
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - rewrite
    - ssl
  notify:
    - restart apache
  when:
    - apache_ssl_set
  tags:
    ssl
    rewrite

- name: "disable the default sites"
  command: a2dissite {{ item }}
  args:
    removes: "/etc/apache2/sites-enabled/{{ item }}"
  with_items:
    - 000-default
    - 000-default.conf
    - default
    - default.conf
  notify:
    - restart apache
