---
# tasks file for ansible-apache

- name: "install apache2"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - libapache2-mod-scgi
  tags:
    install

- name: Load a variable file based on the OS type, or a default if not found.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: "install php modules"
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_php_install_modules }}"
  tags:
    php
    scgi

- name: "enable apache modules"
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - scgi
    - "{{ apache_php_enable_module }}"
  notify:
    - restart apache
  tags:
    php
    scgi

- name: "enable apache ssl modules"
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - rewrite
    - ssl
  notify:
    - restart apache
  when:
    - apache_ssl_set
  tags:
    ssl
    rewrite

- name: "disable the default sites"
  command: a2dissite {{ item }}
  args:
    removes: "/etc/apache2/sites-enabled/{{ item }}"
  with_items:
    - 000-default
    - 000-default.conf
    - default
    - default.conf
  notify:
    - restart apache
